
ID = 'OP_ID'

INC   = 'OP_INC'
MAX   = 'OP_MAX'
MIN   = 'OP_MIN'
RW    = 'OP_RW'
READ  = 'OP_READ'
WRITE = 'OP_WRITE'

DAT_ACCESS_TYPES = [READ, WRITE, RW, INC]
GBL_ACCESS_TYPES = [READ, INC, MAX, MIN]
