
# Makefile generation is a wip




{{ opt.name }}:
	$(FC) $(OPT) $(FMODS) -c \
		{{ source_files|join(' ') }} 
	$(MPIF90) $(OPT) $(OPENMP) $(FLINK) -o exe_{{ opt.name }} -lop2_for_seq \
		{{ object_files|join(' ') }} 

clean:
	rm -f exe_{{ opt.name }} \
		{{ source_files|join(' ') }} \
		{{ object_files|join(' ') }}